Add OTEL Tracing
ldebruijn/graphql-protect pull request #55
Opened 2024-01-31 13:36 UTC by aacoba

This MR Adds OpenTelemetry based tracing to Protect.
It uses [autoprop](https://pkg.go.dev/go.opentelemetry.io/contrib/propagators/autoprop) and [autoexport](https://pkg.go.dev/go.opentelemetry.io/contrib/exporters/autoexport).
This makes it configurable with the OTEL SDK configuration properties.
This maybe makes it a bit harder to configure as configuration is not done via protect.yml, but it does allow automatic instrumentation if the OTEL environment variables are set in the runtime environments.
If desired, I can also remove the autoconfiguration and make it all dependant on protect.yml, but this will extend the config by quite a bit and we will have to keep updating the config and code with newer options that we don't necessarily use for our own usecase.

2024-01-31 14:00 UTC, ldebruijn approved these changes

2024-01-31 14:02 UTC, ldebruijn commented
Could you add documentation for configuring tracing?

2024-01-31 14:04 UTC, aacoba commented on internal/app/otel/otel.go
> +func SetupOTelSDK(ctx context.Context, version string) (shutdown func(context.Context) error, err error) {
stolen from the otel getting started documentation, but I think in this case it makes it clear that it is a shutdown hook that you need to call to cleanly shutdown the tracer

2024-01-31 14:05 UTC, aacoba commented
> Could you add documentation for configuring tracing?

Yes I will, the branch is still WIP

2024-02-01 19:04 UTC, ldebruijn requested changes
Thanks again for a great contribution! Just a few bits that could use improvement.

I do agree with your approach to configure OTEL via the environment variables, rather than configuring it via protect.yml 👍

2024-02-01 19:04 UTC, ldebruijn commented on docs/run/tracing.md
> +        image: eu.gcr.io/bolcom-stg-shop-api-a1c/graphql-protect:v0.11.0 # Replace with the appropriate version
we also tag with `latest`, perhaps a good idea to use for these examples

2024-02-01 19:04 UTC, ldebruijn commented on internal/http/proxy/proxy.go
> +	RedactedHeaders []string `yaml:"redactedheaders"`
Could you add this configuration option to your documentation please?

2024-02-01 19:07 UTC, ldebruijn commented on internal/http/proxy/proxy.go
> +	RedactedHeaders []string `yaml:"redactedheaders"`
also maybe update it to `redacted_headers` for readability

2024-02-08 07:06 UTC, ldebruijn approved these changes

2024-02-08 07:07 UTC, merged